### ISSUE TITLE
Duplicate Icons 

### ISSUE THREAD

**Issue by SVonKarajann** [Orfium/orfium-ictinus#109]
Comparing[ Abstract Icons Index](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/master/commits/latest/files/b92ab9f6-c2c1-4d0b-ad7a-f6bb373d2b49/layers/EAB00FCD-9037-4563-B9A1-E3B8B1528391?collectionId=c318021f-9130-411c-8701-e5e623760f27&collectionLayerId=f1a1d56f-a6c5-4679-99de-d27c0412269f&mode=build&selected=root-DC7F79A0-4BFE-483F-9C9B-B4131BE51AB4) and the [Icons Gallery on Design System](https://ictinus.herokuapp.com/?path=/story/design-system-icon--icons-gallery) some Icons have A) the same name and different .svg file or B) the same .svg file and different name:

A) alert, hourglass
B) {named in Abstract} - same as {named in Design System}
- **arrow** - same as **fatArrow**
- **analytics Videos** - same as **linked**
- **checkMarkLarge** - same as **check**
- **checkMarkSmall** - same as **checkMark**
- **claimList** - same as **income**
- **claimerAnalytics** - same as **financialChart**
- **errorLarge** - same as **error**
- **errorSmall** - same as **closeTag**
- **inactiveClaims** - same as **timeOut**
- **globalReviewl** - same as **globalItem**
- **leadGeneration** - same as **youtube** 
- **potentialClaim** - same as **percentage**
- **reviewHistory** - same as **restore**
- **settings** - same as **auto** (already inserted)
- **systemManagement** - same as **processManagement**
- **videoConfirmation** - same as **stamp**
- **warning** - same as **alert**

**Comment by panvourtsis** [comment]
Moved to jira https://orfium.atlassian.net/browse/NDS-604
