### ISSUE TITLE
DatePicker StoryShot is not generated

### ISSUE THREAD

**Issue by michalisKout** [Orfium/orfium-ictinus#123]
StoryShots plugin is not able to generate a snapshot file for DatePicker. 

The reason is that it cannot map the imported CSS module (`import 'react-day-picker/lib/style.css'`) as a valid module.
Based on the jest's documentation, the solution is simple and can be found [here](https://jestjs.io/docs/en/webpack).

Although, following the above solution, jest will throw an exception regarding the emotion's `css` keyword. 

**Jest Exception:** `TypeError: Cannot convert a Symbol value to a string.`

**Steps to reproduce issue:** 
1. add the following property to moduleNameMapper property of` jest.config.js` file
  ` '\\.(css|less)$': '<rootDir>/__mocks__/styleMock.js',`
2. run the command `yarn test:run` to execute tests.

**Outcome:** Resolve the described issue above and generate a storyshot for the DatePicker component.

**Comment by panvourtsis** [comment]
this is resolved in the next version
