### ISSUE TITLE
Passing theme in emotion styled component versioning problem 

### ISSUE THREAD

**Issue by NikosCha** [Orfium/orfium-ictinus#133]
**Describe the bug**
When the latest version of @emotion/styled is used, the theme is not passed in the children components 

**To Reproduce**
1. Use `@emotion/styled: "^11.0.0" `and `@orfium/ictinus": "^1.5.0"`
2. Wrap your app with the ictinus theme provider     `<IctinusThemeProvider > ... </IctinusThemeProvider>`
3. Try to use the Ictinus theme in a styled component eg `fill: ${props => props.theme.utils.getColor("mint", 400)};`
4. You will get an error since theme is an empty object.

**Expected behavior**
We should be able to use the Ictinus theme in a styled component since we pass it through the ictinus theme provider. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36039128/101484034-aa7f1c00-3961-11eb-894f-4997d6d0e1b0.png)
![image](https://user-images.githubusercontent.com/36039128/101484059-b8cd3800-3961-11eb-8a71-3cb1c82ae0ef.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
It works properly with `"@emotion/styled": "^10.0.27"` because the theme is visible in the styled components.

**Comment by panvourtsis** [comment]
problem that is being solved in the `next` version of v5
