### ISSUE TITLE
Dropdown list expands over the input

### ISSUE THREAD

**Issue by elektracodes** [Orfium/orfium-ictinus#182]
![Screenshot_4](https://user-images.githubusercontent.com/11538983/107060321-7c8e4a80-67df-11eb-915a-de6df2715508.png)

The dropdown width expands to fit the text inside. I am not sure this is the expected behavior...

**Comment by panvourtsis** [comment]
This is actually the behaviour that the design team wanted. We can discuss this with katerina if you want and revisit
