### ISSUE TITLE
Drawer has absolute positioning and content behind it is hidden

### ISSUE THREAD

**Issue by whosyourtaco** [Orfium/orfium-ictinus#211]
Before: 
![image](https://user-images.githubusercontent.com/13350837/110631492-3f86f080-81af-11eb-8166-685c345c1646.png)

After:
![image](https://user-images.githubusercontent.com/13350837/110631539-4ca3df80-81af-11eb-9ec9-4c736918418c.png)

Let's see how we can fix this, because it also affects the way the layout should render when the drawer is open (right now it just gets wider and hides more content)

**Comment by Christos-Zacharopoulos** [comment]
@panvourtsis  @whosyourtaco This is not a bug. In [DES1366-DES1200] the navigation is positioned above the page content.

If it's position is relative while it's closed , then upon expanding the whole content will move left when we change the position property to absolute.

**Comment by whosyourtaco** [comment]
After talking with @Christos-Zacharopoulos, it has become apparent that this is not a bug but a feature 🎉 

We will handle this in our project.

For reference, here's the link: https://cmo-portal-c-feat-por-6-bji9vk.herokuapp.com/ 

Can't really tell you the screen width since I was zoomed in but it was enough to trigger the `breakpoints.des1200` breakpoint.

**Comment by panvourtsis** [comment]
;) thats why i asked him that and i wanted to be sure the ticket is here for future reference. Thanks @whosyourtaco and @Christos-Zacharopoulos 🎊
