### ISSUE TITLE
Improve code examples in the docs

### ISSUE THREAD

**Issue by mkarajohn** [Orfium/orfium-ictinus#418]
Code views like this
![image](https://user-images.githubusercontent.com/3789226/145019223-4e84c611-07a2-47e5-a0b0-4007d12e3ee0.png)
do not help at all when you want to see the code for a usage example

**Comment by mkarajohn** [comment]
I hit a dead end on my part, so I [asked on SO](https://stackoverflow.com/questions/70569577/in-storybook-how-can-you-display-the-full-source-of-a-component-in-the-show-cod)

I have the suspicion that what I asked is not possible at all and the only solution is to rewrite the stories in order to include the showcase code in the `.stories.mdx` files instead of importing the showcase components.

**Comment by panvourtsis** [comment]
Moved to jira: https://orfium.atlassian.net/browse/NDS-607
