### ISSUE TITLE
Overlapping CSS rules in Select.style and TextInputBase.style

### ISSUE THREAD

**Issue by mkarajohn** [Orfium/orfium-ictinus#439]
[These](https://github.com/Orfium/orfium-ictinus/blob/master/src/components/Select/Select.style.ts#L22-L25) style rules in `Select.style` apply the same visuals as [these](https://github.com/Orfium/orfium-ictinus/blob/master/src/components/TextInputBase/TextInputBase.style.ts#L92-L100) rules from `TextInputBase.style`.

Since `TextInputBase` is a building component of `Select` the `Select.style` rule seems to be a leftover. It is also more error prone because it targets a child element on which it applies the rule, while the `TextInputBase.style` rule targets the element in question directly and is also a better solution since it simply uses the `:focus-within` selector.

If it's confirmed that both rules are not needed we should go ahead and remove the one from `Select`

cc @Christos-Zacharopoulos @panvourtsis @whosyourtaco since you are the contributors to these lines.

**Comment by Christos-Zacharopoulos** [comment]
This, along with others, will be resolved in the global states ticket.

**Comment by panvourtsis** [comment]
I think the above links are no longer valid. Is that true? @mkarajohn
