### ISSUE TITLE
Breadcrumb component

### ISSUE THREAD

**Issue by panvourtsis** [Orfium/orfium-ictinus#5]
This will be a component in order to show the navigation to the user. It will be consisted by 3 types of breadcrumb, simple, simple with options and advanced

All dropdowns, spacings and buttons that are going to used are going to be from the design system.

See reference below:
![image](https://user-images.githubusercontent.com/6433679/84120161-18439d00-aa3e-11ea-81e8-85de8b0cd00b.png)

**Comment by elektracodes** [comment]
Calling dibs on that one

**Comment by michalisKout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #5 https://github.com/Orfium/orfium-ictinus/issues/5](https://trello.com/c/NQKm1Gc2/10-issue-5-https-githubcom-orfium-orfium-ictinus-issues-5)

**Comment by panvourtsis** [comment]
do we have an official board for this project?
