### ISSUE TITLE
Extract static values out of function execution

### ISSUE THREAD

**Issue by mkarajohn** [Orfium/orfium-ictinus#569]
https://github.com/Orfium/orfium-ictinus/blob/709dea2727b5c054552cb6f364d3c9f6f33852f0/src/theme/index.ts#L13-L14
and
https://github.com/Orfium/orfium-ictinus/blob/709dea2727b5c054552cb6f364d3c9f6f33852f0/src/theme/index.ts#L24-L26

The functions described here can be executed outside of the function body and their return values can exist as static values, instead of recalculating them during runtime

**Comment by panvourtsis** [comment]
@mkarajohn I feel these are necessary for getting the correct theme values though when a theme changes with a button press.

Theming is a property that can change on the fly, this mechanism changes on the v5.

**Comment by mkarajohn** [comment]
Changing on a button press !== must be recalculated on button press
In any case, it's changed in the newer version, so I am closing this.
