### ISSUE TITLE
Support prop types of HTMLInputElement without listing them in the props list in the docs section.

### ISSUE THREAD

**Issue by michalisKout** [Orfium/orfium-ictinus#72]
**Issue Description:** 
 Extending a component's props with HTMLInputElement will result on listing all the HTMLInputElement props in the docs file of the storybook. 

example:
Component's props
- id 
- label
- style
HTMLInputElement
- onClick
- onFocus
- onChange
etc..

The consumer should be agnostic of the HTMLInputElement prop types. We would like to ignore these props from displaying them in the docs section of the storybook.

**Comment by NikosCha** [comment]
It doesn't seem to be an issue anymore. Tested at v2 branch.

**Comment by panvourtsis** [comment]
Tested and is working after v2
